version: "3.4"

volumes:
  #mcc_mariadb:
  mcc_mongodb:
  mcc_elasticsearch:
  # mcc_backup:
  #   external:
  #     name: mcc_backup

networks:
  mcc:
    driver: overlay

services:
  # SSL-Gateway
  traefik:
    image: repo.moovit24.de:443/mcc_traefik:4.0.5.3
    command: traefik --configFile=/etc/traefik-ssl/traefik.toml
    restart: always
    depends_on:
      - hw
      - fx
      - co
      - users
      - streams
      - preferences
      - metadata
      - logging
      - amqp
      - license
      - language
      - rabbitmq
    networks:
      - mcc
    ports:
     - target: 80
       published: 80
       protocol: tcp
       mode: host
     - target: 443
       published: 443
       protocol: tcp
       mode: host
     - target: 8000
       published: 8000
       protocol: tcp
       mode: host
#     - target: 22
#       published: 222
#       protocol: tcp
#       mode: host
    volumes:
      - /root/traefik:/acme
      - /root/traefik/traefik.toml:/traefik.toml
      - /root/traefik/certs/:/certs
      - /var/run/docker.sock:/var/run/docker.sock

  hp:
     image: repo.moovit24.de:443/mcp_hp:4.9.1.5
     restart: always
     container_name: mcp_hp
     networks:
       - mcc

  hw:
     image: repo.moovit24.de:443/mcp_hw:4.9.1.3
     restart: always
     container_name: mcp_hw
     networks:
       - mcc

  fx:
     image: repo.moovit24.de:443/mcp_fx:4.9.1.1
     restart: always
     container_name: mcp_fx
     environment:
       parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.co.url=http://co:8101/v1/co 
        --mcc.io.url=http://io:8102/v1/io         
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     volumes:
       - /mnt/helmut:/Users/Shared/Helmut24
       #- /samba/helmut:/Users/Shared/Helmut24
     networks:
       - mcc
     depends_on:
       - mongodb
       - preferences

  io:
     image: repo.moovit24.de:443/mcp_io:4.9.1.3
     restart: always
     container_name: mcp_io
     environment:
       parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.co.url=http://co:8101/v1/co 
        --mcc.io.url=http://io:8102/v1/io         
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     volumes:
       - /mnt/helmut:/Users/Shared/Helmut24
       #- /samba/helmut:/Users/Shared/Helmut24
     networks:
       - mcc
     depends_on:
       - mongodb
       - preferences

  co:
     image: repo.moovit24.de:443/mcp_co:4.9.1.2
     restart: always
     container_name: mcp_co
     environment:
      parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.co.url=http://co:8101/v1/co 
        --mcc.io.url=http://io:8102/v1/io 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     volumes:
       - /mnt/helmut:/Users/Shared/Helmut24
       #- /samba/helmut:/Users/Shared/Helmut24
     networks:
       - mcc
     depends_on:
       - mongodb

  users:
     image: repo.moovit24.de:443/mcc_users:4.9.1.1
     restart: always
     container_name: mcc_users
     environment:
      parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.co.url=http://co:8101/v1/co 
        --mcc.io.url=http://io:8102/v1/io 
        --mcc.users.url=http://users:8000/v1/members
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     volumes:
       - /etc/machine-id:/etc/unique-id
       - /mnt/helmut:/Users/Shared/Helmut24
     networks:
       - mcc
     depends_on:
       - mongodb

  streams:
     image: repo.moovit24.de:443/mcc_streams:4.9.1.5
     restart: always
     container_name: mcc_streams
     environment:
      parameters: 
        --spring.data.mongodb.host=mongodb
        --spring.rabbitmq.host=rabbitmq
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.co.url=http://co:8101/v1/co 
        --mcc.io.url=http://io:8102/v1/io 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     networks:
       - mcc
     volumes:
       - /mnt/helmut:/Users/Shared/Helmut24
     depends_on:
       - mongodb
       - rabbitmq

  preferences:
    image: repo.moovit24.de:443/mcc_preferences:4.9.1.0
    restart: always
    container_name: mcc_preferences
    environment:
      parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
    networks:
      - mcc
    depends_on:
      - mongodb
      - users

  metadata:
    image: repo.moovit24.de:443/mcc_metadata:4.9.1.0
    restart: always
    container_name: mcc_metadata
    environment:
      parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
    networks:
      - mcc
    depends_on:
      - mongodb
      
  logging:
    image: repo.moovit24.de:443/mcc_logging:4.9.1.0
    restart: always
    environment:
      parameters: 
        --spring.elasticsearch.rest.uris=http://elasticsearch:9200 
        --spring.elasticsearch.rest.timeout=2000
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
    networks:
      - mcc
    depends_on:
      - mongodb

  amqp:
    image: repo.moovit24.de:443/mcc_amqp:4.9.1.3
    restart: always
    container_name: mcc_amqp
    environment:
      parameters: 
        --spring.rabbitmq.host=rabbitmq
        --spring.elasticsearch.rest.uris=http://elasticsearch:9200 
        --spring.elasticsearch.rest.timeout=2000
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
    networks:
      - mcc
    depends_on:
      - rabbitmq

  license:
    image: repo.moovit24.de:443/mcc_license:4.9.1.4
    restart: always
    container_name: mcc_license
    environment:
      parameters: 
        --spring.data.mongodb.host=mongodb 
        --mcc.fx.url=http://fx:8100/v1/fx 
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
    volumes:
      - /etc/machine-id:/machine-id
      - /etc/helmut4:/version
    networks:
      - mcc
    depends_on:
      - mongodb

  language:
    image: repo.moovit24.de:443/mcc_language:4.9.1.0
    restart: always
    container_name: mcc_language
    environment:
      parameters: 
        --spring.data.mongodb.host=mongodb
        --mcc.users.url=http://users:8000/v1/members 
        --mcc.stream.url=http://streams:8001/v1/streams 
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
    networks:
      - mcc
    depends_on:
      - mongodb

  # Databases
  # mariadb:
  #   image: repo.moovit24.de:443/mcc_mariadb:latest
  #   restart: always
  #   container_name: mcc_mariadb
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - mcc
  #   volumes:
  #     - mcc_mariadb:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ***REMOVED***
  mongoadmin:
    image: repo.moovit24.de:443/mcc_mongodb_admin:4.0.1.1
    restart: always
    networks:
      - mcc
    depends_on:
      - mongodb
    ports:
      - 8199:8199

  mongodb:
    image: repo.moovit24.de:443/mcc_mongodb:4.2.0.0
    restart: always
    container_name: mcc_mongodb
    ports:
      - 27017:27017
    networks:
      - mcc
    volumes:
      - mcc_mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ***REMOVED***
  
  mongobackup:
    image: repo.moovit24.de:443/mcc_mongodb_backup:4.1.0.4
    restart: always
    networks:
      - mcc
    volumes:
       - /mnt/helmut/backup:/backup
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USER: root
      MONGODB_PASS: ***REMOVED***
      CRON_TIME: "0 */4 * * *"
      MAX_BACKUPS:  180
      INIT_BACKUP: "true"
      
  # AMQP
  rabbitmq:
    image: repo.moovit24.de:443/mcc_rabbitmq:4.1.0.0
    restart: always
    container_name: mcc_rabbitmq
    #environment:
      #RABBITMQ_DEFAULT_USER: root
      #RABBITMQ_DEFAULT_PASS: ***REMOVED*** 
    ports:
      - 15674:15674
      #- 15672:15672
      #- 5672:5672
    networks:
      - mcc

  hk:
     image: repo.moovit24.de:443/mcp_hk:4.9.1.0
     restart: always
     environment:
       parameters:
        --spring.data.mongodb.host=mongodb
        --spring.rabbitmq.host=rabbitmq
        --mcc.fx.url=http://fx:8100/v1/fx
        --mcc.co.url=http://co:8101/v1/co
        --mcc.io.url=http://io:8102/v1/io
        --mcc.users.url=http://users:8000/v1/members
        --mcc.stream.url=http://streams:8001/v1/streams
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     volumes:
      - /etc/localtime:/etc/localtime:ro
     networks:
       - mcc
     depends_on:
       - mongodb

  cronjob:
     image: repo.moovit24.de:443/mcc_cronjob:4.9.1.0
     restart: always
     environment:
       parameters:
        --spring.data.mongodb.host=mongodb
        --spring.rabbitmq.host=rabbitmq
        --mcc.fx.url=http://fx:8100/v1/fx
        --mcc.co.url=http://co:8101/v1/co
        --mcc.io.url=http://io:8102/v1/io
        --mcc.hk.url=http://hk:8103/v1/hk
        --mcc.users.url=http://users:8000/v1/members
        --mcc.stream.url=http://streams:8001/v1/streams
        --mcc.preference.url=http://preferences:8002/v1/preferences
        --mcc.metadata.url=http://metadata:8003/v1/metadata
        --mcc.logging.url=http://logging:8004/v1/logging/helmut
        --mcc.amqp.url=http://amqp:8005/v1/amqp/send
        --mcc.license.url=http://license:8006/v1/license
        --mcc.language.url=http://language:8007/v1/language
     volumes:
      - /etc/localtime:/etc/localtime:ro
     networks:
       - mcc
     depends_on:
       - mongodb
  xml-generator:
     image: repo.moovit24.de:443/helmutxmlapi:0.0.15-VPMS
     restart: always
     #container_name: xml_generator
     volumes:
       - /mnt/helmut:/Users/Shared/Helmut24
       #- /samba/helmut:/Users/Shared/Helmut24
     networks:
       - mcc
     depends_on:
       - io