{{- if .Values.mongobackup.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongobackup
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
    app: mongobackup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongobackup
  template:
    metadata:
      labels:
        app: mongobackup
        {{- include "helmut4.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmut4.serviceAccountName" . }}
      
      containers:
        - name: mongobackup
          image: "{{ .Values.global.registry }}/{{ .Values.mongobackup.image }}:{{ .Values.mongobackup.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          
          env:
            - name: MONGODB_HOST
              value: "mongodb-0.mongodb-headless"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USER
              value: {{ .Values.mongodb.auth.rootUser }}
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: CRON_TIME
              value: {{ .Values.mongobackup.cronTime | quote }}
            - name: MAX_BACKUPS
              value: {{ .Values.mongobackup.maxBackups | quote }}
            - name: INIT_BACKUP
              value: {{ .Values.mongobackup.initBackup | quote }}
          
          resources:
            {{- toYaml .Values.mongobackup.resources | nindent 12 }}
          
          volumeMounts:
            - name: backup
              mountPath: /backup
      
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: mongodb-backup-pvc
{{- end }}
