{{- if and .Values.mongodb.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
---
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret-json
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- if and .Values.docker.username .Values.docker.password }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"%s\", \"auth\": \"%s\"}}}" .Values.docker.registry .Values.docker.username .Values.docker.password .Values.docker.email (printf "%s:%s" .Values.docker.username .Values.docker.password | b64enc) | b64enc }}
{{- else }}
data:
  .dockerconfigjson: e30K  # Empty JSON object {}
{{- end }}
