{{- if and .Values.docker.username .Values.docker.password }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.docker.registry (printf "%s:%s" .Values.docker.username .Values.docker.password | b64enc) | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret-json
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- if and .Values.docker.username .Values.docker.password }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"%s\", \"auth\": \"%s\"}}}" .Values.docker.registry .Values.docker.username .Values.docker.password .Values.docker.email (printf "%s:%s" .Values.docker.username .Values.docker.password | b64enc) | b64enc }}
{{- else }}
data:
  .dockerconfigjson: e30K  # Empty JSON object {}
{{- end }}
