{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
      protocol: TCP
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        {{- include "helmut4.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmut4.serviceAccountName" . }}
      
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.elasticsearch.port }}
              name: http
              protocol: TCP
          
          env:
            - name: discovery.type
              value: "single-node"
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "false"
          
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmut4.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.elasticsearch.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.size }}
{{- end }}
