apiVersion: v2
name: helmut4
description: A Helm chart for Helmut4 microservices application
type: application
version: 1.4.0
appVersion: "4.12"
icon: https://www.helmut.de/wp-content/uploads/sites/5/2024/08/helmut-logo-small.png
keywords:
  - helmut4
  - microservices
  - mongodb
  - rabbitmq
home: https://github.com/moovit-sp-gmbh/helmut4-helm-chart
sources:
  - https://github.com/moovit-sp-gmbh/helmut4-helm-chart
maintainers:
  - name: Rafael Hutter
    email: r.hutter@moovit.de
dependencies:
  - name: mongodb
    version: "0.10.3"
    repository: "oci://registry-1.docker.io/cloudpirates"
  - name: rabbitmq
    version: "0.7.10"
    repository: "oci://registry-1.docker.io/cloudpirates"
