apiVersion: v2
name: helmut4
description: A Helm chart for Helmut4 microservices application
type: application
version: 1.0.0
appVersion: "4.12"
keywords:
  - helmut4
  - microservices
  - mongodb
  - rabbitmq
home: https://github.com/moovit24/helmut4-helm-chart
sources:
  - https://github.com/moovit24/helmut4-helm-chart
maintainers:
  - name: Rafael Hutter
    email: r.hutter@moovit.de
dependencies:
  - name: mongodb
    version: "0.10.3"
    repository: "oci://registry-1.docker.io/cloudpirates"
  - name: rabbitmq
    version: "0.7.10"
    repository: "oci://registry-1.docker.io/cloudpirates"
